### ISSUE TITLE
Error when installing assemblyline-v4-service (ssdeep)

### ISSUE THREAD

**Issue by godfriedmeesters** [CybercentreCanada/assemblyline_client#4]
### Problem

`pip3 install --user assemblyline-v4-service`  gives exception:

```
Traceback (most recent call last):
      File "/tmp/pip-install-7he_8rmp/ssdeep/.eggs/cffi-1.14.4-py3.8-linux-x86_64.egg/cffi/ffiplatform.py", line 51, in _build
        dist.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/usr/lib/python3.8/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
### Context

Ubuntu 20.04.1 LTS

### Solution

`sudo apt-get install python-dev libfuzzy-dev`

**Comment by cccs-sgaron** [comment]
This was reported on the wrong repo. Also you should not have to install assemblyline-v4-service unless its to put inside a service container. Just using the client, you really don't need this.
